baseURL = 'https://girishchaulagain.github.io/'
languageCode = 'en-us'
title = 'Girish Chaulagain'
theme = 'PaperMod'

[params]
    [params.profileMode]
        enabled = true
        title = "Sup"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/GirishChaulagain"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/girish7"
